# -*- coding: utf-8 -*-
"""Untitled19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjCHryqIU6Pif16_k9VHUQrE7Yh-E2LF
"""

def kasallik_tashxisi(belgi):
 if belgi =="istima":
  return "Parasetamol iching"
 elif belgi =="bosh og'rigi":
  return "Trimol iching"
 elif belgi =="gripp":
  return "taylol hot iching"
 elif belgi =="Yuraginiz og'risa":
  return "Kardiomagnil iching"
 elif belgi =="zarda bo'lsangiz":
  return "Mezim iching"
 elif belgi =="ko'zingiz og'risa" :
  return "Okulistga murojat qiling"
 elif belgi =="tishingiz og'risa":
  return "Bol nol iching"
 elif belgi =="turli hil toshmalar chiqsa ":
  return "kojinniga murojat qiling"
 elif belgi =="bo'g'inlaringiz og'risa":
  return "diklofenak gel surting"
 elif belgi =="allergiyangiz qo'zg'asa":
  return "Allerg iching"
belgi=input("Kasallik belgisini kiriting")
natija=kasallik_tashxisi(belgi)
print(natija)

def vrach_xonasi(belgi):
 if belgi =="Nevropotolog":
  return "1-etaj 1-xona"
 elif belgi =="stomotolog":
  return "2-etaj 3-xona"
 elif belgi =="okulist ":
  return "2-etaj 2-xona"
 elif belgi =="Endikrinolog":
  return "1-etaj 7-xona"
 elif belgi =="Gnikolog":
  return "2-etaj 4-xona "
 elif belgi =="Labalatoriya" :
  return "1-etaj 2-xona"
 elif belgi =="xirurg":
  return "2-etaj 9-xona"
 elif belgi =="umumiy shifokor":
  return "1-etaj 6-xona"
belgi=input("Kerakli vrachni kiriting")
natija=vrach_xonasi(belgi)
print(natija)